export const TRAINEE_CREATED_WITH_SUBSCRIBE = "TRAINEE_CREATED_WITH_SUBSCRIBE";
export const TRAINEE_UPDATED_WITH_SUBSCRIBE = "TRAINEE_UPDATED_WITH_SUBSCRIBE";
export const TRAINEE_DELETED_WITH_SUBSCRIBE = "TRAINEE_DELETED_WITH_SUBSCRIBE";
